require "user.options"
require "user.keymaps"
require "user.plugins"
-- require "user.colorscheme"
require "user.bufferline"
require "user.windline"
require "user.nvim-tree"
require "user.indentline"
require "user.autopairs"
require "user.telescope"
require "user.autosave"
require "user.lastplace"
require "user.lsp"
--require "user.cmp"
require "user.treesitter"

